//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backend.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ModelDb : DbContext
    {
        public ModelDb()
            : base("name=ModelDb")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Action> Actions { get; set; }
        public virtual DbSet<Ingredient> Ingredients { get; set; }
        public virtual DbSet<Recipe> Recipes { get; set; }
        public virtual DbSet<Step> Steps { get; set; }
    
        public virtual ObjectResult<GetRecipeBySearch_Result> GetRecipeBySearch(string p_Name, string p_MainIngridient, string p_Nationality)
        {
            var p_NameParameter = p_Name != null ?
                new ObjectParameter("p_Name", p_Name) :
                new ObjectParameter("p_Name", typeof(string));
    
            var p_MainIngridientParameter = p_MainIngridient != null ?
                new ObjectParameter("p_MainIngridient", p_MainIngridient) :
                new ObjectParameter("p_MainIngridient", typeof(string));
    
            var p_NationalityParameter = p_Nationality != null ?
                new ObjectParameter("p_Nationality", p_Nationality) :
                new ObjectParameter("p_Nationality", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetRecipeBySearch_Result>("GetRecipeBySearch", p_NameParameter, p_MainIngridientParameter, p_NationalityParameter);
        }
    }
}
